#To be used only when developing the keycloak image
version: "3.8"

services:

  db:
    container_name: "keycloak-db-dev"
    image: "mysql:5.7"
    ports: 
      - "5001:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
    networks: 
      - keycloak
    restart: unless-stopped

  # Exporting doesn't work unless DEBUG mode is disabled.
  keycloak:
    container_name: "keycloak-dev"
    depends_on: 
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: "keycloak-dev:latest"
    volumes:
    - "./realm-config:/opt/jboss/keycloak/imports" #Get exports in your local filesystem immediately
    ports:
      - "8001:8080"
      - "8443:8443"
      - "8787:8787"
    # Override CMD to get local env config
    command: ["-b 0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/hermes-export-dev.json", "-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: keycloak-db-dev
      DB_VENDOR: mysql
      DB_USER: root
      DB_PASSWORD: root
      DEBUG: "false"
      DEBUG_PORT: "*:8787"
    networks: 
      - keycloak
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  keycloak: